name: Release

on:
  push:
    tags:
      - 'actionstest[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare notes
        run: |
          # Extract changelog entries between this and previous version headers
          escaped_version=$(echo ${GITHUB_REF_NAME#actionstest} | sed -e 's/[]\/$*.^[]/\\&/g')
          awk "BEGIN{inrelease=0} /## \[${escaped_version}\]/{inrelease=1;next} /## \[[0-9]+\.[0-9]+\.[0-9]+.*\]/{inrelease=0;exit} {if (inrelease) print}" CHANGELOG.md \
            > RELEASE_NOTES.txt

          # Write PRERELEASE env if tag name has any suffix after vMAJOR.MINOR.PATCH
          if [[ ${GITHUB_REF_NAME} =~ ^actionstest[0-9]+\.[0-9]+\.[0-9]+.+ ]]; then
            PRERELEASE="true" >> $GITHUB_ENV
          fi
      - name: Release
        run: |
          cat RELEASE_NOTES.txt
          echo "This is prerelease: $PRERELEASE"
