name: Test

on:
  - push
  - pull_request

env:
  CGO_LDFLAGS_ALLOW: "-s|-w"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: darthsim/imgproxy-ci:202311211816
    strategy:
      matrix:
        go-version: ["1.22.x", "1.21.x"]
        vips-version: ["8.15", "8.14", "8.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache mods
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
      - name: Download mods
        run: go mod download
      - name: Test
        run: go test ./...
        env:
          LD_LIBRARY_PATH: "/usr/local/lib:/root/vips/${{ matrix.vips-version }}/lib"
          PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:/root/vips/${{ matrix.vips-version }}/lib/pkgconfig"
